"""Phase A/B deterministic ingestion orchestration.

설계 출처: docs/Orchestration_Construction (00 §7.1 Final implementation stance,
07 노드 설계, 11 구현 청사진). Layer 1 = 결정적 수집 cycle, 신규 설치 0.

심볼은 PEP 562 lazy import로 노출한다. 이유: ``__init__``이 실행 모듈
``run_orchestration_cycle``을 즉시 import하면
``python -m ingestion.orchestration.run_orchestration_cycle`` 실행 시 runpy가
"이미 sys.modules에 있다"는 RuntimeWarning을 낸다. lazy 노출로 공개 API는
유지하면서 그 경고를 제거한다.
"""
from __future__ import annotations

import importlib
from typing import TYPE_CHECKING

__all__ = [
    "run_cycle",
    "CycleReport",
    "SourceOutcome",
    "DEFAULT_SOURCES",
    "to_event_seed",
    "SUCCESS_STATUSES",
    "SourceSchedule",
    "is_due",
    "select_due_sources",
    "SourceProfile",
    "load_source_profiles",
    "profiles_to_schedules",
    "is_live_eligible",
    "StrategyDecision",
    "decide_strategy",
    "load_last_run_state",
    "save_last_run_state",
    "record_last_run",
    # Phase D
    "ApiKeyReadiness",
    "audit_api_key_readiness",
    "summarize_readiness",
    "canonicalize_url",
    "ArticleCandidate",
    "parse_artifact_text",
    "BodyExtractionState",
    "assess_body_state",
    "assess_candidate_body",
    "CandidateExpansionReport",
    "expand_seed_to_article_candidates",
    "LiveSmokeResult",
    "audit_live_smoke",
    "summarize_live_smoke",
    # Phase D-P / E-0
    "SourceExpansionAudit",
    "audit_artifact_text",
    "audit_artifact_file",
    "summarize_expansion",
    "QualityPreGateResult",
    "evaluate_pre_gate",
    "normalize_published_at",
    "compute_duplicate_key",
    "assess_boilerplate",
    "summarize_pre_gate",
    # Phase E-1
    "AuditTraceEvent",
    "TraceRecorder",
    "SourceBodyAudit",
    "SourceBodyAuditResult",
    "CandidateInspection",
    "audit_source_body",
    "summarize_body_audits",
    "SourceBodyReport",
    "classify_production_readiness",
    "build_source_report",
    "summarize_reports",
    # Phase E-2
    "SourceRevivalPlan",
    "StrategyAttemptRecord",
    "BodyFetchResult",
    "StructuredSignalCandidate",
    "SourceRevivalResult",
    "RevivalEvidence",
    "build_revival_plan",
    "fetch_article_body",
    "to_structured_signal_candidates",
    "build_eventqueue_record",
    "check_eventqueue_readiness",
    "classify_final_status",
    "summarize_revival",
    # Phase E-3
    "finalize_unresolved_status",
    "LadderBodyResult",
    "fetch_body_with_ladder",
    "SourceStrategyMemory",
    "save_strategy_memory",
    "load_strategy_memory",
    "preferred_strategy_for",
    "is_known_dead_end",
    "decide_strategy_with_memory",
    # Phase F
    "NormalizedTime",
    "normalize_time",
    "normalize_record_times",
    "ProductionSourceState",
    "ProductionStrategyDecision",
    "derive_production_state",
    "decide_production_strategy",
    "load_production_state",
    "save_production_state",
    "summarize_states",
    "RateLimitDecision",
    "RateLimitGovernor",
    "detect_rate_limit_signal",
    "QuarantineDecision",
    "evaluate_quarantine",
    "is_quarantine_active",
    "ProductionRunPlan",
    "build_production_run_plan",
    "DedupDecision",
    "DedupIndex",
    "compute_record_key",
    "dedup_records",
    "CrossSourceDedupResult",
    "cluster_records",
    "RawEventPayload",
    "RawEventBridgeWriter",
    "map_eq_record_to_raw_event",
    "bridge_records",
    "Alert",
    "build_monitoring_summary",
    "write_monitoring_report",
    # Phase G
    "VendorRouteResult",
    "fetch_vendor",
    "has_vendor_route",
    "SourceReadinessGap",
    "build_gap_matrix",
    "summarize_gaps",
    "RescueDecision",
    "decide_rescue",
    "route_all",
    "BodyRescueResult",
    "rescue_news_body",
    "SourceValueDecision",
    "decide_source_value",
    # Phase G-2
    "SourcePolicyProbeResult",
    "probe_source_policy",
    "DCInsideStrategyResult",
    "collect_dcinside",
    "GdeltStrategyResult",
    "collect_gdelt",
    "HostRateGate",
    "HostGateDecision",
    "GoogleTrendsAssessment",
    "assess_google_trends",
    "SourceSupervisorDecision",
    "LastChanceSourceResurrection",
    "classify_resurrection",
    # Phase G-3
    "SourceCapability",
    "capability_for",
    "StrategyGraph",
    "StrategyNode",
    "build_strategy_graph",
    "reject_unsafe",
    "ToolPlan",
    "build_tool_plan",
    "EvidenceGateResult",
    "evaluate_evidence",
    "gate_records",
    "FinalSourceClosure",
    "decide_final_status",
    "classify_final_closure",
]

_SYMBOL_MODULE = {
    "run_cycle": "run_orchestration_cycle",
    "CycleReport": "run_orchestration_cycle",
    "SourceOutcome": "run_orchestration_cycle",
    "DEFAULT_SOURCES": "run_orchestration_cycle",
    "to_event_seed": "event_seed",
    "SUCCESS_STATUSES": "event_seed",
    "SourceSchedule": "cycle_planner",
    "is_due": "cycle_planner",
    "select_due_sources": "cycle_planner",
    "SourceProfile": "source_profile",
    "load_source_profiles": "source_profile",
    "profiles_to_schedules": "source_profile",
    "is_live_eligible": "source_profile",
    "StrategyDecision": "strategy_router",
    "decide_strategy": "strategy_router",
    "load_last_run_state": "cycle_state",
    "save_last_run_state": "cycle_state",
    "record_last_run": "cycle_state",
    # Phase D
    "ApiKeyReadiness": "api_readiness",
    "audit_api_key_readiness": "api_readiness",
    "summarize_readiness": "api_readiness",
    "canonicalize_url": "canonical_url",
    "ArticleCandidate": "article_candidate",
    "parse_artifact_text": "artifact_parser",
    "BodyExtractionState": "body_state",
    "assess_body_state": "body_state",
    "assess_candidate_body": "body_state",
    "CandidateExpansionReport": "seed_expansion",
    "expand_seed_to_article_candidates": "seed_expansion",
    "LiveSmokeResult": "live_smoke_audit",
    "audit_live_smoke": "live_smoke_audit",
    "summarize_live_smoke": "live_smoke_audit",
    # Phase D-P / E-0
    "SourceExpansionAudit": "production_audit",
    "audit_artifact_text": "production_audit",
    "audit_artifact_file": "production_audit",
    "summarize_expansion": "production_audit",
    "QualityPreGateResult": "quality_pre_gate",
    "evaluate_pre_gate": "quality_pre_gate",
    "normalize_published_at": "quality_pre_gate",
    "compute_duplicate_key": "quality_pre_gate",
    "assess_boilerplate": "quality_pre_gate",
    "summarize_pre_gate": "quality_pre_gate",
    # Phase E-1
    "AuditTraceEvent": "audit_trace",
    "TraceRecorder": "audit_trace",
    "SourceBodyAudit": "source_body_audit",
    "SourceBodyAuditResult": "source_body_audit",
    "CandidateInspection": "source_body_audit",
    "audit_source_body": "source_body_audit",
    "summarize_body_audits": "source_body_audit",
    "SourceBodyReport": "source_body_report",
    "classify_production_readiness": "source_body_report",
    "build_source_report": "source_body_report",
    "summarize_reports": "source_body_report",
    # Phase E-2
    "SourceRevivalPlan": "full_source_revival",
    "StrategyAttemptRecord": "full_source_revival",
    "BodyFetchResult": "full_source_revival",
    "StructuredSignalCandidate": "full_source_revival",
    "SourceRevivalResult": "full_source_revival",
    "RevivalEvidence": "full_source_revival",
    "build_revival_plan": "full_source_revival",
    "fetch_article_body": "full_source_revival",
    "to_structured_signal_candidates": "full_source_revival",
    "build_eventqueue_record": "full_source_revival",
    "check_eventqueue_readiness": "full_source_revival",
    "classify_final_status": "full_source_revival",
    "summarize_revival": "full_source_revival",
    # Phase E-3
    "finalize_unresolved_status": "full_source_revival",
    "LadderBodyResult": "body_fetch_strategy",
    "fetch_body_with_ladder": "body_fetch_strategy",
    "SourceStrategyMemory": "source_strategy_memory",
    "save_strategy_memory": "source_strategy_memory",
    "load_strategy_memory": "source_strategy_memory",
    "preferred_strategy_for": "source_strategy_memory",
    "is_known_dead_end": "source_strategy_memory",
    "decide_strategy_with_memory": "strategy_router",
    # Phase F
    "NormalizedTime": "time_normalizer",
    "normalize_time": "time_normalizer",
    "normalize_record_times": "time_normalizer",
    "ProductionSourceState": "production_state",
    "ProductionStrategyDecision": "production_state",
    "derive_production_state": "production_state",
    "decide_production_strategy": "production_state",
    "load_production_state": "production_state",
    "save_production_state": "production_state",
    "summarize_states": "production_state",
    "RateLimitDecision": "rate_limit_governor",
    "RateLimitGovernor": "rate_limit_governor",
    "detect_rate_limit_signal": "rate_limit_governor",
    "QuarantineDecision": "quarantine",
    "evaluate_quarantine": "quarantine",
    "is_quarantine_active": "quarantine",
    "ProductionRunPlan": "production_scheduler",
    "build_production_run_plan": "production_scheduler",
    "DedupDecision": "eventqueue_dedup",
    "DedupIndex": "eventqueue_dedup",
    "compute_record_key": "eventqueue_dedup",
    "dedup_records": "eventqueue_dedup",
    "CrossSourceDedupResult": "cross_source_dedup",
    "cluster_records": "cross_source_dedup",
    "RawEventPayload": "bridge_to_raw_events",
    "RawEventBridgeWriter": "bridge_to_raw_events",
    "map_eq_record_to_raw_event": "bridge_to_raw_events",
    "bridge_records": "bridge_to_raw_events",
    "Alert": "monitoring",
    "build_monitoring_summary": "monitoring",
    "write_monitoring_report": "monitoring",
    # Phase G
    "VendorRouteResult": "vendor_api_routes",
    "fetch_vendor": "vendor_api_routes",
    "has_vendor_route": "vendor_api_routes",
    "SourceReadinessGap": "source_readiness_closure",
    "build_gap_matrix": "source_readiness_closure",
    "summarize_gaps": "source_readiness_closure",
    "RescueDecision": "rescue_router",
    "decide_rescue": "rescue_router",
    "route_all": "rescue_router",
    "BodyRescueResult": "body_rescue_ladder",
    "rescue_news_body": "body_rescue_ladder",
    "SourceValueDecision": "source_value_policy",
    "decide_source_value": "source_value_policy",
    # Phase G-2
    "SourcePolicyProbeResult": "source_policy_probe",
    "probe_source_policy": "source_policy_probe",
    "DCInsideStrategyResult": "dcinside_strategy",
    "collect_dcinside": "dcinside_strategy",
    "GdeltStrategyResult": "gdelt_strategy",
    "collect_gdelt": "gdelt_strategy",
    "HostRateGate": "host_rate_gate",
    "HostGateDecision": "host_rate_gate",
    "GoogleTrendsAssessment": "google_trends_strategy",
    "assess_google_trends": "google_trends_strategy",
    "SourceSupervisorDecision": "source_supervisor",
    "LastChanceSourceResurrection": "last_chance_source_resurrection",
    "classify_resurrection": "last_chance_source_resurrection",
    # Phase G-3
    "SourceCapability": "source_capability",
    "capability_for": "source_capability",
    "StrategyGraph": "strategy_graph",
    "StrategyNode": "strategy_graph",
    "build_strategy_graph": "strategy_graph",
    "reject_unsafe": "strategy_graph",
    "ToolPlan": "tool_plan",
    "build_tool_plan": "tool_plan",
    "EvidenceGateResult": "evidence_gate",
    "evaluate_evidence": "evidence_gate",
    "gate_records": "evidence_gate",
    "FinalSourceClosure": "final_source_closure",
    "decide_final_status": "final_source_closure",
    "classify_final_closure": "final_source_closure",
}


def __getattr__(name: str):
    module = _SYMBOL_MODULE.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    return getattr(importlib.import_module(f"{__name__}.{module}"), name)


def __dir__() -> list[str]:
    return sorted(__all__)


if TYPE_CHECKING:  # 정적 분석/IDE 자동완성용 (런타임 import 아님)
    from ingestion.orchestration.cycle_planner import (  # noqa: F401
        SourceSchedule,
        is_due,
        select_due_sources,
    )
    from ingestion.orchestration.event_seed import (  # noqa: F401
        SUCCESS_STATUSES,
        to_event_seed,
    )
    from ingestion.orchestration.cycle_state import (  # noqa: F401
        load_last_run_state,
        record_last_run,
        save_last_run_state,
    )
    from ingestion.orchestration.run_orchestration_cycle import (  # noqa: F401
        DEFAULT_SOURCES,
        CycleReport,
        SourceOutcome,
        run_cycle,
    )
    from ingestion.orchestration.source_profile import (  # noqa: F401
        SourceProfile,
        load_source_profiles,
        profiles_to_schedules,
    )
    from ingestion.orchestration.strategy_router import (  # noqa: F401
        StrategyDecision,
        decide_strategy,
    )
